[storage]
# Default storage driver, must be set for proper operation.
driver = "overlay"

# Temporary storage location
runroot = "/run/containers/storage"

graphroot = "/var/lib/containers/storage"

[storage.options]
additionalimagestores = [
  "/usr/lib/containers/storage",
  "/mnt/podman-host-storage"
]

# Options controlling how storage is populated when pulling images.
[storage.options.pull_options]

[storage.options.overlay]

# mountopt specifies comma separated list of extra mount options
mountopt = "nodev,metacopy=on"
